def merge_and_clean_fiverr_data(dfs):
    """Merges the relational Fiverr dataframes and handles missing values."""
    # 1. Start with the main manual data table
    main_df = dfs['manual_data'].copy()
    
    # 2. Merge Dimension Tables sequentially using the relational IDs
    merged_df = main_df.merge(
        dfs['gig_title'], left_on='Gig Title', right_on='gig_title_id', how='left'
    ).merge(
        dfs['about_the_gig'], left_on='About the Gig', right_on='about_gig_id', how='left'
    ).merge(
        dfs['about_me'], left_on='About Me', right_on='about_me_id', how='left'
    )
    
    # Drop the redundant ID columns generated by the merge
    columns_to_drop = ['gig_title_id', 'about_gig_id', 'about_me_id']
    merged_df = merged_df.drop(columns=columns_to_drop)
    
    # 3. Handle Missing Values (Imputation)
    # Fill missing text fields with descriptive strings
    merged_df['about_me'] = merged_df['about_me'].fillna('No bio provided')
    merged_df['about_gig'] = merged_df['about_gig'].fillna('No gig description provided')
    merged_df['gig_title'] = merged_df['gig_title'].fillna('No title provided')
    
    # Handle optional package parameters safely
    merged_df['Revisions'] = merged_df['Revisions'].fillna('0')
    merged_df['Included'] = merged_df['Included'].fillna('None specified')
    
    # 4. Standardize Text Formats for analysis (stripping spaces, lowercase headers)
    merged_df.columns = merged_df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
    
    print(True, f"Master Dataset Created! Shape: {merged_df.shape}")
    return merged_df

# Run the cleaning pipeline
master_df = merge_and_clean_fiverr_data(data)
# View a slice of our clean data
master_df[['gig_title', 'cost', 'stars', 'reviews']].head()

print("==================================================")
print("     FIVERR CONSULTING TOOLKIT - INITIAL REPORT    ")
print("==================================================\n")

# Executive Summary Stats
total_gigs = len(master_df)
avg_cost = master_df['cost'].mean()
avg_stars = master_df['stars'].mean()
total_reviews = master_df['reviews'].sum()

print(f"📊 Total Gigs Sampled: {total_gigs}")
print(f"💰 Average Gig Price: ${avg_cost:.2f}")
print(f"⭐ Average Star Rating: {avg_stars:.2f} / 5.0")
print(f"💬 Total Customer Reviews in Sample: {total_reviews:,}\n")

print("--------------------------------------------------")
print("  Top 5 Most Expensive Tier Options Analyzed  ")
print("--------------------------------------------------")
top_expensive = master_df.sort_values(by='cost', ascending=False).head(5)
for idx, row in top_expensive.iterrows():
    print(f"- ${row['cost']} | Delivery: {row['delivery_timeline_days']} days | Title: {row['gig_title'][:60]}...")

